### ISSUE TITLE
generate_payout_data_script.py error due to codec

### ISSUE THREAD

**Issue by david-a-wheeler** [david-a-wheeler/holophrasm#1]
~~~~
dwheeler@metamath:~/holophrasm$ time python3 generate_payout_data_script.py
included 3651590 tokens from set.mm
proposition: 29330
tautologies: 12843
wff variables: 18
class variables: 27
set variables: 20
936 constructor axioms with arity 0
38 constructor axioms with arity 1
57 constructor axioms with arity 2
38 constructor axioms with arity 3
8 constructor axioms with arity 4
3 constructor axioms with arity 5
1 constructor axioms with arity 6
1 constructor axioms with arity 7
1 constructor axioms with arity 8

training steps: 1209897
validation steps: 119785
test steps: 158116
max proof step depth: 68
Config(): added 1088 tokens to dictionary
Traceback (most recent call last):
  File "generate_payout_data_script.py", line 18, in <module>
    pd.initialize_interface(lm, 'searcher')
  File "/home/dwheeler/holophrasm/build_payout_data_set.py", line 38, in initialize_interface
    global_interface = interface.ProofInterface(lm, directory=directory, skip_payout=True)
  File "/home/dwheeler/holophrasm/interface.py", line 42, in __init__
    self.gen_var.load(directory+'/gen.weights')
  File "/home/dwheeler/holophrasm/models.py", line 180, in load
    vs = pickle.load(handle)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 0: ordinal not in range(128)
~~~~

**Comment by thepok** [comment]
i got it running on windows and python3 with the help of this: https://rebeccabilbro.github.io/convert-py2-pickles-to-py3/
